import numpy as np
# ar=np.arange(10)
# print(ar.tolist())
# ar=np.zeros((3,3))
# print(ar)
# ar1=np.ones((4,4))
# print(ar1)
# print(np.arange(2,21,2))
# ar=np.array([[1,2,3],[4,5,6]])
# print(ar.shape)
# print(ar.size)
# print(ar.ndim)
# print(ar.dtype)
# ar=np.arange(12)
# print(ar)
# print(ar.reshape((3,4)))
# print(ar.reshape((2,6)))
# print(ar[:3])
# print(ar[-2:])
# print(ar[2:5])
# a=np.array([1,2,3])
# b=np.array([4,5,6])
# print(a+b)
# print(a-b)
# print(a*b)
# print(a/b)
ar=np.array([5,10,15,20,25])
print(np.mean(ar))
print(np.median(ar))
print(np.std(ar))
print(np.max(ar))
print(np.min(ar))
print(np.sum(ar))